### ISSUE TITLE
大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！

### ISSUE THREAD

**Issue by aitangbodan** [egbertYeah/mt-yolov6_tensorrt#1]

**Comment by egbertYeah** [comment]
好的，等几天更新

**Comment by aitangbodan** [comment]
感谢大佬！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月23日(星期五) 下午5:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1)





 
好的，等几天更新

**Comment by egbertYeah** [comment]
> 感谢大佬！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年9月23日(星期五) 下午5:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1) 好的，等几天更新 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，我在这个链接https://github.com/egbertYeah/YOLOv6/tree/dev中实现了Yolov6 2.0的Deepstream 推理。

**Comment by aitangbodan** [comment]
谢谢大佬的开源！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "egbertYeah/mt-yolov6_tensorrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1)





  
感谢大佬！
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年9月23日(星期五) 下午5:02 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1) 好的，等几天更新 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你好，我在这个链接https://github.com/egbertYeah/YOLOv6/tree/dev中实现了Yolov6 2.0的Deepstream 推理。

**Comment by egbertYeah** [comment]
那我关闭这个issue了。

**Comment by aitangbodan** [comment]
大佬，我按照您的步骤刚刚完成了yolov6s_v2的deepstream推理。这次更新实现了yolov6s_v2_reopt的deepstream推理吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "egbertYeah/mt-yolov6_tensorrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1)





  
感谢大佬！
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年9月23日(星期五) 下午5:02 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1) 好的，等几天更新 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你好，我在这个链接https://github.com/egbertYeah/YOLOv6/tree/dev中实现了Yolov6 2.0的Deepstream 推理。

**Comment by egbertYeah** [comment]
没有测试过，你可以自己测试

**Comment by aitangbodan** [comment]
好的！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "egbertYeah/mt-yolov6_tensorrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 上午9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1)





 
没有测试过，你可以自己测试

**Comment by aitangbodan** [comment]
大佬，您训练的时候有DFL损失函数吗？我训练的时候没有。。

**Comment by egbertYeah** [comment]
我直接测试了yolov6n-repopt-qat的onnx文件，是可以用的。
![image](https://user-images.githubusercontent.com/39177405/193235129-18a66427-5575-418c-a0bf-b8e7990d79aa.png)

**Comment by aitangbodan** [comment]
嗯嗯，我的问题解决了，感谢大佬回复！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "egbertYeah/mt-yolov6_tensorrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月30日(星期五) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1)





 
我直接测试了yolov6n-repopt-qat的onnx文件，是可以用的。

**Comment by egbertYeah** [comment]
你使用QAT训练网络了？

**Comment by aitangbodan** [comment]
目前在进行第一步：使用training_mode='hyper_search'策略训练模型。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月30日(星期五) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1)





 
你使用QAT训练网络了？

**Comment by egbertYeah** [comment]
厉害，我看了这个过程还挺复杂的，做这个量化还得请教你呢。

**Comment by aitangbodan** [comment]
我是菜鸟。。还没踩坑呢。。走一步看一步




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月30日(星期五) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1)





 
厉害，我看了这个过程还挺复杂的，做这个量化还得请教你呢。

**Comment by egbertYeah** [comment]
你是打算用自己的数据集训练还是COCO？

**Comment by aitangbodan** [comment]
自己的汽车数据集，目前就9000张左右，还在找。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月30日(星期五) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [egbertYeah/mt-yolov6_tensorrt] 大佬可以更新一下yolov6v2版本的deepstream吗？ 感谢！ (Issue #1)





 
你是打算用自己的数据集训练还是COCO？
